/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-02-26 06:13:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prcInput_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/exe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/exe/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1676536392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"kor\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>대지에스텍</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/remixicon@latest/fonts/remixicon.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/view/css/style.css?v=");
      out.print(System.currentTimeMillis());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/common/js/common.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/flatpickr\"></script>\r\n");
      out.write("    <script src=\"https://npmcdn.com/flatpickr/dist/l10n/ko.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <nav>\r\n");
      out.write("            <!-- <div class=\"nav-logo\">\r\n");
      out.write("                <img src=\"web/images/daeji_logo.svg\" alt=\"대지에스텍 로고\">\r\n");
      out.write("                <h1>대지에스텍</h1>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            \r\n");
      out.write("            <ul>\r\n");
      out.write("                <li onclick=\"location.href='mgtRpt'\">경영보고</li>\r\n");
      out.write("                <li onclick=\"location.href='prodRpt'\">생산보고</li>\r\n");
      out.write("                <li onclick=\"location.href='busiRpt'\">영업보고</li>\r\n");
      out.write("                <li onclick=\"location.href='fncDaily'\">자금일보</li>\r\n");
      out.write("                <li onclick=\"location.href='atdDaily'\">일일계근</li>\r\n");
      out.write("                <li class=\"active\" onclick=\"location.href='prcInput'\">단가입력</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <section id=\"textWrapper\">\r\n");
      out.write("            <div class=\"title-compart\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\"><path d=\"M2 20H22V22H2V20ZM4 12H6V19H4V12ZM9 12H11V19H9V12ZM13 12H15V19H13V12ZM18 12H20V19H18V12ZM2 7L12 2L22 7V11H2V7ZM12 8C12.5523 8 13 7.55228 13 7C13 6.44772 12.5523 6 12 6C11.4477 6 11 6.44772 11 7C11 7.55228 11.4477 8 12 8Z\" fill=\"rgba(58,78,132,1)\"></path></svg>\r\n");
      out.write("                <h2>단가입력</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <article class=\"section-control-compartment ft-wrap mi-0 al w-full mb-8 h-auto\">\r\n");
      out.write("                <div class=\"labeled-input-binder ft-al-between\">\r\n");
      out.write("                    <label for=\"\" class=\"form-input-label\">계근일자</label>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-filter-date\">\r\n");
      out.write("                        <div class=\"form-input-date\">\r\n");
      out.write("                            <input type=\"text\" id=\"SRCH_EVAL_SDT\" name=\"sYmdFrom\" class=\"date-picker flatpickr-input\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sYmdFrom }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly=\"readonly\" >\r\n");
      out.write("                            <div class=\"date-calendar-icon\">\r\n");
      out.write("                                <i class=\"ri-calendar-event-line\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ~\r\n");
      out.write("                        <div class=\"form-input-date\">\r\n");
      out.write("                            <input type=\"text\" id=\"SRCH_EVAL_EDT\" name=\"sYmdTo\" class=\"date-picker flatpickr-input\" value= ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sYmdTo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly=\"readonly\">\r\n");
      out.write("                            <div class=\"date-calendar-icon\">\r\n");
      out.write("                                <i class=\"ri-calendar-event-line\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"labeled-input-binder ml-12 ft-al-between\">\r\n");
      out.write("                    <label for=\"\" class=\"form-input-label\">담당자</label>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-input-search w-full\">\r\n");
      out.write("                        <input type=\"text\" id=\"COGRUP_NM\" name=\"COGRUP_NM\" class=\"search-result h-auto\" readonly=\"\" onclick=\"showCOGRUP()\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                        <div class=\"search-icon\" onclick=\"showCOGRUP()\">\r\n");
      out.write("                            <i class=\"ri-search-line\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"labeled-input-binder ml-12 ft-al-between\">\r\n");
      out.write("                    <label for=\"\" class=\"form-input-label\">입출고구분</label>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-filter-date gap-12 bg-gray\">\r\n");
      out.write("                        <div class=\"form-input-checker\">\r\n");
      out.write("                            <input type=\"radio\" name=\"sKeraType\" id=\"ftInput\" value=\"IN\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sKeraType == 'IN' ? 'checked=\"checked\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"checker-element\">\r\n");
      out.write("                            <label for=\"chkIn\">입고</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-input-checker\">\r\n");
      out.write("                            <input type=\"radio\" name=\"sKeraType\" id=\"ftOutput\" value=\"OUT\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sKeraType == 'OUT' ? 'checked=\"checked\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"checker-element\">\r\n");
      out.write("                            <label for=\"chkOut\">출고</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"labeled-input-binder ml-12 ft-al-between\">\r\n");
      out.write("                    <label for=\"\" class=\"form-input-label\">마감구분</label>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-filter-date gap-12 bg-gray\">\r\n");
      out.write("                        <div class=\"form-input-checker\">\r\n");
      out.write("                            <input type=\"radio\" name=\"jCheck\" id=\"cCate_all\" value=\"ALL\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jCheck == 'ALL' ? 'checked=\"checked\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"checker-element\">\r\n");
      out.write("                            <label for=\"cCate_all\">전체</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-input-checker\">\r\n");
      out.write("                            <input type=\"radio\" name=\"jCheck\" id=\"cCate_end\" value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jCheck == '1' ? 'checked=\"checked\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"checker-element\">\r\n");
      out.write("                            <label for=\"cCate_end\">마감</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-input-checker\">\r\n");
      out.write("                            <input type=\"radio\" name=\"jCheck\" id=\"cCate_nEnd\" value=\"\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jCheck == '' ? 'checked=\"checked\"' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" class=\"checker-element\">\r\n");
      out.write("                            <label for=\"cCate_end\">미마감</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"ml-auto common-button\" type=\"button\" onclick=\"submitForm()\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"rgba(255,255,255, .5)\"><path d=\"M18.031 16.6168L22.3137 20.8995L20.8995 22.3137L16.6168 18.031C15.0769 19.263 13.124 20 11 20C6.032 20 2 15.968 2 11C2 6.032 6.032 2 11 2C15.968 2 20 6.032 20 11C20 13.124 19.263 15.0769 18.031 16.6168ZM16.0247 15.8748C17.2475 14.6146 18 12.8956 18 11C18 7.1325 14.8675 4 11 4C7.1325 4 4 7.1325 4 11C4 14.8675 7.1325 18 11 18C12.8956 18 14.6146 17.2475 15.8748 16.0247L16.0247 15.8748Z\"></path></svg>\r\n");
      out.write("                    조회\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"common-button\" type=\"button\" style=\"--button-face-color: #0075ff;\" onclick=\"saveData()\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"rgba(255,255,255,.5)\"><path d=\"M7 19V13H17V19H19V7.82843L16.1716 5H5V19H7ZM4 3H17L21 7V20C21 20.5523 20.5523 21 20 21H4C3.44772 21 3 20.5523 3 20V4C3 3.44772 3.44772 3 4 3ZM9 15V19H15V15H9Z\"></path></svg>\r\n");
      out.write("                    저장\r\n");
      out.write("                </button>\r\n");
      out.write("            </article>\r\n");
      out.write("            <!-- 테이블 시작 -->\r\n");
      out.write("            <div id=\"\" class=\"section-contents scrolling-table common-table-wrap\">\r\n");
      out.write("                <table id=\"\" class=\"common-data-table amount-table\" style=\"border-block: 0;\">\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col class=\"tb-cell-number\" />\r\n");
      out.write("                        <col class=\"tb-cell-shortname\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-title\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("\r\n");
      out.write("                        <col class=\"tb-cell-instname\" />\r\n");
      out.write("                        <col class=\"tb-cell-instname\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("                        <col class=\"tb-cell-year\" />\r\n");
      out.write("\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>마감</th>\r\n");
      out.write("                            <th>계근일자</th>\r\n");
      out.write("                            <th>거래구분</th>\r\n");
      out.write("                            <th>거래처명</th>\r\n");
      out.write("                            <th>담당자</th>\r\n");
      out.write("                            <th>차량번호</th>\r\n");
      out.write("                            <th>등급</th>\r\n");
      out.write("\r\n");
      out.write("                            <th>감량</th>\r\n");
      out.write("                            <th>인수량</th>\r\n");
      out.write("                            <th>운반비</th>\r\n");
      out.write("\r\n");
      out.write("                            <th>공차중량</th>\r\n");
      out.write("                            <th>총중량</th>\r\n");
      out.write("                            <th>기준단가</th>\r\n");
      out.write("                            <th>적용단가</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("</tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 테이블 끝 -->\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 담당자 Modal -->\r\n");
      out.write("    <dialog id=\"modalCogrup\" class=\"common-modal\">\r\n");
      out.write("\t    <div class=\"common-modal-container\">\r\n");
      out.write("\t        <div class=\"modal-titlebar\">\r\n");
      out.write("\t            <div class=\"modal-icon\">\r\n");
      out.write("\t                <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" opacity=\".5\"><path fill=\"currentColor\" d=\"M12 14V16C8.68629 16 6 18.6863 6 22H4C4 17.5817 7.58172 14 12 14ZM12 13C8.685 13 6 10.315 6 7C6 3.685 8.685 1 12 1C15.315 1 18 3.685 18 7C18 10.315 15.315 13 12 13ZM12 11C14.21 11 16 9.21 16 7C16 4.79 14.21 3 12 3C9.79 3 8 4.79 8 7C8 9.21 9.79 11 12 11ZM21.4462 20.032L22.9497 21.5355L21.5355 22.9497L20.032 21.4462C19.4365 21.7981 18.7418 22 18 22C15.7909 22 14 20.2091 14 18C14 15.7909 15.7909 14 18 14C20.2091 14 22 15.7909 22 18C22 18.7418 21.7981 19.4365 21.4462 20.032ZM18 20C19.1046 20 20 19.1046 20 18C20 16.8954 19.1046 16 18 16C16.8954 16 16 16.8954 16 18C16 19.1046 16.8954 20 18 20Z\"></path></svg>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div class=\"modal-label\">\r\n");
      out.write("\t                중앙부처 검색\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <section class=\"modal-contents h-md-body\">\r\n");
      out.write("\t        \t<div class=\"modal-section-title h-auto mt-12\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"modal-section-icon\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" opacity=\".5\"><path fill=\"currentColor\" d=\"M18.031 16.6168L22.3137 20.8995L20.8995 22.3137L16.6168 18.031C15.0769 19.263 13.124 20 11 20C6.032 20 2 15.968 2 11C2 6.032 6.032 2 11 2C15.968 2 20 6.032 20 11C20 13.124 19.263 15.0769 18.031 16.6168ZM16.0247 15.8748C17.2475 14.6146 18 12.8956 18 11C18 7.1325 14.8675 4 11 4C7.1325 4 4 7.1325 4 11C4 14.8675 7.1325 18 11 18C12.8956 18 14.6146 17.2475 15.8748 16.0247L16.0247 15.8748Z\"></path></svg>\r\n");
      out.write("                    <span class=\"modal-section-label\">담당자 검색</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\t            \r\n");
      out.write("\t            <div class=\"modal-search-compartment\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-input-text\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"srchKeyword\" name=\"srchKeyword\" class=\"input-element\" placeholder=\"키워드 입력...\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\r\n");
      out.write("\t                <button type=\"button\" id=\"btnSearch\" class=\"common-button\" style=\"--button-face-color: #32c05a;\" onclick = \"searchEmp()\">\r\n");
      out.write("\t                    <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" opacity=\".5\"><path fill=\"currentColor\" d=\"M10.0007 15.1709L19.1931 5.97852L20.6073 7.39273L10.0007 17.9993L3.63672 11.6354L5.05093 10.2212L10.0007 15.1709Z\"></path></svg>\r\n");
      out.write("\t                    <span class=\"common-button-label\">검색</span>\r\n");
      out.write("\t                </button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- 테이블 시작 -->\r\n");
      out.write("\t            <div class=\"section-contents scrolling-table for-md-scr mi-0 mh-auto\">\r\n");
      out.write("\t                <table id=\"tablePIC\" class=\"common-data-table uploaded-table\">\r\n");
      out.write("\t                    <colgroup>\r\n");
      out.write("\t                        <col class=\"tb-cell-instname\"/>\r\n");
      out.write("\t                    </colgroup>\r\n");
      out.write("\t                    <thead>\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                            <th class=\"left\">영업사원목록</th>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                    </thead>\r\n");
      out.write("\t                    <tbody>\r\n");
      out.write("\t                    \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style = \"text-align:left\" class=\"tb-cell-body-title cursor-pointer\" onclick=\"selectCogrup(this)\">전체</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t                    \t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("</tbody>\r\n");
      out.write("\t                </table>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t        <div class=\"modal-control-compartment\">\r\n");
      out.write("\t            <button type=\"button\" class=\"common-button\" onclick=\"closeCOGRUP()\">\r\n");
      out.write("\t                <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"common-button-icon\" viewBox=\"0 0 24 24\" width=\"16\" height=\"16\"><path d=\"M12.0007 10.5865L16.9504 5.63672L18.3646 7.05093L13.4149 12.0007L18.3646 16.9504L16.9504 18.3646L12.0007 13.4149L7.05093 18.3646L5.63672 16.9504L10.5865 12.0007L5.63672 7.05093L7.05093 5.63672L12.0007 10.5865Z\"></path></svg>\r\n");
      out.write("\t                <span class=\"common-button-label\">닫기</span>\r\n");
      out.write("\t            </button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</dialog>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const modalCogrup = document.getElementById('modalCogrup');\r\n");
      out.write("\r\n");
      out.write("    function showCOGRUP() {\r\n");
      out.write("        modalCogrup.showModal();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeCOGRUP() {\r\n");
      out.write("        modalCogrup.close();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(window).load(function(){\r\n");
      out.write("        //달력\r\n");
      out.write("    \tconst fpOption = {\r\n");
      out.write("                locale: 'ko', // 한국어 locale 설정\r\n");
      out.write("                dateFormat: 'Y-m-d',\r\n");
      out.write("                disableMobile: true\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            flatpickr.localize(flatpickr.l10ns.ko); // 한국어로 설정\r\n");
      out.write("            $(\".date-picker\").flatpickr(fpOption);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function initializeFlatpickr() {\r\n");
      out.write("        const fpOption = {\r\n");
      out.write("            locale: 'ko', // 한국어 locale 설정\r\n");
      out.write("            dateFormat: 'Y-m-d',\r\n");
      out.write("            disableMobile: true\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        flatpickr.localize(flatpickr.l10ns.ko); // 한국어로 설정\r\n");
      out.write("        $(\".date-picker\").flatpickr(fpOption);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function submitForm() {\r\n");
      out.write("\t    var sYmdFrom = document.getElementsByName('sYmdFrom')[0].value;\r\n");
      out.write("\t    var sYmdTo = document.getElementsByName('sYmdTo')[0].value;\r\n");
      out.write("\t    //var sUtPrcYn = document.querySelector('input[name=\"sUtPrcYn\"]:checked').value;\r\n");
      out.write("\t    var sKeraType = document.querySelector('input[name=\"sKeraType\"]:checked').value;\r\n");
      out.write("\t    var empName = document.getElementsByName('COGRUP_NM')[0].value;\r\n");
      out.write("\t    var jCheck = document.querySelector('input[name=\"jCheck\"]:checked').value;\r\n");
      out.write("\t\r\n");
      out.write("        //alert('날짜 : ' + sYmdFrom + \"~\" + sYmdTo + ', sKeraType: ' + sKeraType);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if(sYmdFrom == '' || sYmdTo == ''){\r\n");
      out.write("        \talert(\"계근일자를 선택해주세요.\");\r\n");
      out.write("        }\r\n");
      out.write("        else{\r\n");
      out.write("        \t// Ajax를 이용하여 컨트롤러로 값을 전송하고 결과를 받음\r\n");
      out.write("    \t    $.ajax({\r\n");
      out.write("    \t        url: \"/exe/prcInput/prclist\", // 실제 컨트롤러의 엔드포인트\r\n");
      out.write("    \t        method: \"POST\",\r\n");
      out.write("    \t        data: {sYmdFrom: sYmdFrom, sYmdTo: sYmdTo, sKeraType: sKeraType, empName: empName, jCheck: jCheck},\r\n");
      out.write("    \t        success: function(response) {\r\n");
      out.write("    \t            // 성공 시 처리\r\n");
      out.write("    \t            // response에는 컨트롤러에서 전송한 데이터가 들어있음\r\n");
      out.write("    \t            //console.log(response);\r\n");
      out.write("    \t            $(\"body\").html(response);\r\n");
      out.write("                    initializeFlatpickr();\r\n");
      out.write("    \t        },\r\n");
      out.write("    \t        error: function(error) {\r\n");
      out.write("    \t            console.error(error);\r\n");
      out.write("    \t        }\r\n");
      out.write("    \t    });\r\n");
      out.write("        }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    function saveData() {\r\n");
      out.write("        var selectedRows = [];\r\n");
      out.write("        var isAnyCheckboxChecked = false;\r\n");
      out.write("        var count = 0;\r\n");
      out.write("        var checkcount = 0;\r\n");
      out.write("        var jCheck = $(\"input[name='jCheck']:checked\").val(); \r\n");
      out.write("        \r\n");
      out.write("        if(jCheck == '1'){\r\n");
      out.write("        \talert(\"마감승인된 자료는 단가수정이 불가능합니다.\");\r\n");
      out.write("        \treturn;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"input[type=checkbox]\").each(function () {\r\n");
      out.write("            if ($(this).prop('checked')) {\r\n");
      out.write("                isAnyCheckboxChecked = true;  // 체크 - 마감된 데이터는 변경 불가능하게 하기 위해서\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("            \tcheckcount++;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            var junpyoid = $(this).closest(\"tr\").find(\"[data-junpyoid]\").data(\"junpyoid\");\r\n");
      out.write("            var inputValue = $(this).closest(\"tr\").find(\".inputText\").val();\r\n");
      out.write("            \r\n");
      out.write("\t\t\tif (inputValue != \"\"){\r\n");
      out.write("\t            var keratype = $(this).closest(\"tr\").find('td:eq(2)').text().trim(); // 3번째 열에 있는 값 가져오기\r\n");
      out.write("\t            count++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            \r\n");
      out.write("            // 만약 입력값이 비어 있다면 placeholder 값으로 대체\r\n");
      out.write("            if (inputValue == \"\") {\r\n");
      out.write("                inputValue = $(this).closest(\"tr\").find(\".inputText\").attr(\"placeholder\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            selectedRows.push({ junpyoid: junpyoid, inputValue: inputValue, keratype: keratype });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        if(checkcount == 0){       \t\r\n");
      out.write("            alert(\"마감승인된 자료는 단가수정이 불가능합니다.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if(count == 0){\r\n");
      out.write("        \talert(\"적용단가를 한개 이상 입력해주세요.\");\r\n");
      out.write("        \treturn;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        console.log(selectedRows);\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"/exe/prcInput/prcupdate\",\r\n");
      out.write("            method: \"POST\",\r\n");
      out.write("            contentType: \"application/json\",\r\n");
      out.write("            data: JSON.stringify(selectedRows),\r\n");
      out.write("            success: function (response) {\r\n");
      out.write("                console.log(response);\r\n");
      out.write("                alert(\"저장되었습니다.\");\r\n");
      out.write("                submitForm();\r\n");
      out.write("            },\r\n");
      out.write("            error: function (error) {\r\n");
      out.write("                console.error(\"에러입니당\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\t \r\n");
      out.write("\t function searchEmp() {\r\n");
      out.write("\t\t    var keyword = document.getElementById('srchKeyword').value.trim();\r\n");
      out.write("\r\n");
      out.write("\t\t    var rows = document.querySelectorAll('#tablePIC tbody tr');\r\n");
      out.write("\r\n");
      out.write("\t\t    rows.forEach(function(row) {\r\n");
      out.write("\t\t        var empName = row.querySelector('td').textContent.trim();\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        if (empName.includes(keyword)) {\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t            row.style.display = 'table-row';\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t        } else {\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            row.style.display = 'none';\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \r\n");
      out.write("\t function selectCogrup(clickedElement) {\r\n");
      out.write("\t\t    var empName = clickedElement.textContent.trim(); \r\n");
      out.write("\t\t    document.getElementById('COGRUP_NM').value = empName;\r\n");
      out.write("\t\t    closeCOGRUP();\r\n");
      out.write("\t\t}\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/prcInput.jsp(163,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("prc");
      // /WEB-INF/views/prcInput.jsp(163,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prcInput.jsp(163,24) '${prcList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${prcList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/prcInput.jsp(163,24) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\r\n");
            out.write("\t\t\t\t\t\t\t \t\t<td style=\"text-align:center\" data-junpyoid=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.junpyoid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"center\">\r\n");
            out.write("    \t\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"checkbox_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.junpyoid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.jcheck == '1' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" onclick = \"return false\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- <td style = \"text-align:center\" data-junpyoid =\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.junpyoid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class = \"center\"><input type=\"checkbox\"></td> -->\r\n");
            out.write("\t                    \t\t\t<td class = \"center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.jdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td style = \"text-align:center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.keratype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td style = \"text-align:left\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.dealernm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.chrgnm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.jbnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.gradenm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input class=\"inputText\" type=\"text\" placeholder=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.applyunitprc }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('"');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.jcheck == '1' ? 'disabled' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" ></td>\r\n");
            out.write("\t                    \t\t</tr>  \r\n");
            out.write("                    \t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(175,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.chagamweight}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(175,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(176,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.acptweight}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(176,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(177,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.transportkumak}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(177,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(178,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.emptyweight}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(178,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
      _jspx_th_fmt_005fformatNumber_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f4_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f4.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(179,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.totweight}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(179,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f4.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f4 = _jspx_th_fmt_005fformatNumber_005f4.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f4);
      _jspx_th_fmt_005fformatNumber_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f4, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f5_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f5.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/prcInput.jsp(180,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prc.stdunitprc}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/prcInput.jsp(180,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f5.setPattern("###,###.#");
      int _jspx_eval_fmt_005fformatNumber_005f5 = _jspx_th_fmt_005fformatNumber_005f5.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f5);
      _jspx_th_fmt_005fformatNumber_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f5, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/prcInput.jsp(233,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("emp");
      // /WEB-INF/views/prcInput.jsp(233,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/prcInput.jsp(233,22) '${empList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${empList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/prcInput.jsp(233,22) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td style = \"text-align:left\" class=\"tb-cell-body-title cursor-pointer\" onclick=\"selectCogrup(this)\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.empnm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>  \r\n");
            out.write("                    \t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
