/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2025-10-10 01:14:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class table_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/daejist7/tomcat/webapps/scm/WEB-INF/lib/spring-security-taglibs-5.7.1.jar!/META-INF/security.tld", Long.valueOf(1652856986000L));
    _jspx_dependants.put("/WEB-INF/views/include/footer.jsp", Long.valueOf(1687502620000L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1694146608000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.7.1.jar", Long.valueOf(1732762432000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("        <meta property=\"og:url\" content=\"https://example.co.kr\">\r\n");
      out.write("        <meta property=\"og:title\" content=\"Website Title\">\r\n");
      out.write("        <meta property=\"og:image\" content=\"https://meta-image.url\">\r\n");
      out.write("        <meta property=\"og:description\" content=\"Website Description\">\r\n");
      out.write("        <meta property=\"og:site_name\" content=\"Website Name\">\r\n");
      out.write("        <meta property=\"og:locale\" content=\"ko_KR\">\r\n");
      out.write("        \r\n");
      out.write("        <meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        <meta id=\"_csrf_name\" name=\"_csrf_name\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("        <!-- OpenGraph Meta Tag -->\r\n");
      out.write("\r\n");
      out.write("        <title>(주) 대지에스텍</title>\r\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/scm/resources/images/icons/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/default.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/common.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/common/wanderface.css\">\r\n");
      out.write("        <!-- Global CSS -->\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\"></script> <!-- jQuery CDN -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"/scm/resources/js/common/default.js\" async></script>\r\n");
      out.write("        <!-- Global JavaScript / jQuery -->\r\n");
      out.write("\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("            <script src=\"./resources/js/common/html5shiv.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("    </head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <a href=\"#mainWrap\" id=\"skipToMain\" tabindex=\"0\">Skip To Main Contents</a> <!-- 메인 컨텐츠 영역으로 건너뛰기 (접근성) -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"wrap\">\r\n");
      out.write("            <header id=\"headPrimary\">\r\n");
      out.write("                <nav id=\"navPrimary\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("                </nav>\r\n");
      out.write("            </header> <!-- #headPrimary -->\r\n");
      out.write("\r\n");
      out.write("            <main id=\"mainWrap\" role=\"main\">\r\n");
      out.write("                <link rel=\"stylesheet\" type=\"text/css\" href=\"/scm/resources/css/main/table.css\">\r\n");
      out.write("                <!-- Per-Page CSS -->\r\n");
      out.write("\r\n");
      out.write("                <script type=\"text/javascript\" src=\"/scm/resources/js/main/table.js?v=");
      out.print(System.currentTimeMillis());
      out.write("\" defer></script>\r\n");
      out.write("                <!-- Per-Page JavaScript -->\r\n");
      out.write("\r\n");
      out.write("                <div id=\"contentView\">\r\n");
      out.write("                    <header id=\"tableHeader\">\r\n");
      out.write("                        <img src=\"/scm/resources/images/main/header.jpg\" class=\"header_image\">\r\n");
      out.write("                        <div class=\"logo\" onclick='location.href=\"http://daejist.co.kr\"'>\r\n");
      out.write("                            <img src=\"/scm/resources/images/main/logo.png\">\r\n");
      out.write("                            <h1>(주)대지에스텍</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"header_text\">철스크랩 전문 기업 <p>(주)대지에스텍</p></div>\r\n");
      out.write("                    </header>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"accChangePW\">\r\n");
      out.write("                        로그인 비밀번호 변경\r\n");
      out.write("                        <input type=\"text\" name=\"txtChangePW\" id=\"txtChangePW\" pattern=\"^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,16}$\" maxlength=\"20\">\r\n");
      out.write("                        <button id=\"chgPw\">변경</button>\r\n");
      out.write("                        <button id=\"logout\">로그아웃</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"listTable\">\r\n");
      out.write("                        <div id=\"tableFilter\">\r\n");
      out.write("                            <span>조회기간</span>\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"date\" name=\"dateRange\" id=\"dateBegin\" data-label=\"시작일자\" min=\"0000-00-00\" max=\"9999-12-31\">\r\n");
      out.write("                            ~\r\n");
      out.write("                            <input type=\"date\" name=\"dateRange\" id=\"dateEnd\" data-label=\"종료일자\" min=\"0000-00-00\" max=\"9999-12-31\">\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"button\" id=\"btnApply\">조회</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"carryOver\">\r\n");
      out.write("                            <button id=\"printOut\">거래명세서</button>\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"txtCarryOver\">이월금액</label>\r\n");
      out.write("                            <input type=\"text\" name=\"txtCarryOver\" id=\"txtCarryOver\" class=\"exclude\" value=\"0\" readonly>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <!-- 13 -->\r\n");
      out.write("                                <col class=\"data_no\">\r\n");
      out.write("                                <col class=\"data_date\">\r\n");
      out.write("                                <col class=\"data_carno\">\r\n");
      out.write("                                <col class=\"data_grade\">\r\n");
      out.write("                                <col class=\"data_weight\">\r\n");
      out.write("                                <col class=\"data_single\">\r\n");
      out.write("                                <col class=\"data_wgtsum\">\r\n");
      out.write("                                <!-- <col class=\"data_logis\"> -->\r\n");
      out.write("                                <col class=\"data_price\">\r\n");
      out.write("                                <col class=\"data_tax\">\r\n");
      out.write("                                <col class=\"data_recieve\">\r\n");
      out.write("                                <col class=\"data_remain\">\r\n");
      out.write("                                <col class=\"data_receipt\">\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th scope=\"col\">순번</th>\r\n");
      out.write("                                    <th scope=\"col\">일자</th>\r\n");
      out.write("                                    <th scope=\"col\">차량번호</th>\r\n");
      out.write("                                    <th scope=\"col\">등급</th>\r\n");
      out.write("                                    <th scope=\"col\">중량</th>\r\n");
      out.write("                                    <th scope=\"col\">단가</th>\r\n");
      out.write("                                    <th scope=\"col\">감량증량</th>\r\n");
      out.write("                                    <!-- <th scope=\"col\">운반비</th> -->\r\n");
      out.write("                                    <th scope=\"col\">공급가액</th>\r\n");
      out.write("                                    <th scope=\"col\">부가세</th>\r\n");
      out.write("                                    <th scope=\"col\">입금액</th>\r\n");
      out.write("                                    <th scope=\"col\">잔액</th>\r\n");
      out.write("                                    <th scope=\"col\">계산서 여부</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("\r\n");
      out.write("                            <tbody data-row-list>\r\n");
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("\r\n");
      out.write("                            <tfoot>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th colspan=\"2\" scope=\"row\">합계</th>\r\n");
      out.write("                                    <td colspan=\"2\"></td>\r\n");
      out.write("                                    <td data-weight>0</td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                    <td data-wgtsum>0</td>\r\n");
      out.write("                                    <!-- <td></td> -->\r\n");
      out.write("                                    <td data-price>0</td>\r\n");
      out.write("                                    <td data-tax>0</td>\r\n");
      out.write("                                    <td data-receive>0</td>\r\n");
      out.write("                                    <td data-remain></td>\r\n");
      out.write("                                    <td></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tfoot>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <template data-table-row>\r\n");
      out.write("                        <tr data-row-id>\r\n");
      out.write("                            <td data-no></td>\r\n");
      out.write("                            <td data-date></td>\r\n");
      out.write("                            <td data-carno></td>\r\n");
      out.write("                            <td data-grade></td>\r\n");
      out.write("                            <td data-weight></td>\r\n");
      out.write("                            <td data-single></td>\r\n");
      out.write("                            <td data-wgtsum></td>\r\n");
      out.write("                            <!--  <td data-logis></td>-->\r\n");
      out.write("                            <td data-price></td>\r\n");
      out.write("                            <td data-tax></td>\r\n");
      out.write("                            <td data-receive></td>\r\n");
      out.write("                            <td data-remain></td>\r\n");
      out.write("                            <td data-receipt></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </template>\r\n");
      out.write("                </div> <!-- #contentView -->\r\n");
      out.write("            </main> <!-- #mainWrap -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<footer id=\"footPrimary\">\r\n");
      out.write("\r\n");
      out.write("            </footer> <!-- #footPrimary -->\r\n");
      out.write("        </div> <!-- #wrap -->\r\n");
      out.write("\r\n");
      out.write("        <aside id=\"toolTip\">\r\n");
      out.write("            <p data-tooltip-text></p>\r\n");
      out.write("        </aside> <!-- #toolTip -->\r\n");
      out.write("\r\n");
      out.write("        <dialog id=\"winModal\" data-layer-type=\"modal\">\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <h2></h2>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" data-modal-close>닫기</button>\r\n");
      out.write("        </dialog>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
      out.write("            ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
